---
cameras: 1
	- camera:
	  pos: {x: 0, y: 0.5, z: 0}
	  dir: {x: 0, y: 0, z: 1}
	  fov: 90
	  background: "./resource/gradient/sunset.yml"
	---
lights: 1
	- type: POINT
	  pos: {x: 0, y: 5, z: 10}
	  color: 0xF6E392
	  intensity: 1.0
	  shadow: HARD
	---
objects: 2
	- type: SPHERE
	  scale: 2
	  pos: {x: 0, y: 1, z: 10}
	  dir: {x: 0, y: 0, z: 1}
	  material:
		  color: 0x364A90
		  ambient: 0.325
		  diffuse: 0.675
		  specular: 1.0
		  shininess: 256
		  reflect: 0
		  refract: 0
	---
	- type: PLANE
	  scale: 1
	  pos: {x: 0, y: -1, z: -1}
	  dir: {x: 0, y: 1, z: 0}
	  material:
		  color: 0xB84D49
		  ambient: 0.025
		  diffuse: 0.975
		  specular: 1.0
		  shininess: 256
		  reflect: 0.5
		  refract: 0
	---
...
