---
cameras: 2
	- camera:
	  pos: {x: 0, y: 1, z: 0}
	  dir: {x: 0, y: 0, z: 0}
	  fov: 130
	  background: "./resource/gradient/sunset.yml"
	---
	- camera:
	  pos: {x: 0, y: 2, z: 0}
	  dir: {x: 0, y: 0, z: 15}
	  fov: 130
	  background: "./resource/gradient/sunset.yml"
	---
lights: 1
	- type: POINT
	  pos: {x: 0, y: 5, z: 10}
	  color: 0xF6E392
	  intensity: 1.6
	  shadow: HARD
	---
objects: 1
	- type: CYLINDER
	  scale: 1
	  pos: {x: 1, y: 0, z: 15}
	  dir: {x: 1, y: 1, z: 0}
	  material:
		  color: 0x7FD4DD
		  ambient: 0.125
		  diffuse: 0.875
		  specular: 2.0
		  shininess: 256
		  reflect: 0
		  refract: 1.73
		  transparency: 1.0
		  absorbtion: 0.7
	---
...
