---
cameras:
	- camera: 1
	  pos: {x: 1, y: 10, z: 0}
	  dir: {x: 0, y: 0, z: 1}
	  fov: 90
	  background:
		  - gradient: {color: 0xC74D2D, pos: 0.0}
		  - gradient: {color: 0xE09879, pos: 0.07}
		  - gradient: {color: 0xF9C863, pos: 0.18}
		  - gradient: {color: 0x55A0B8, pos: 0.36}

	- camera: 2
	  pos: {x: 0, y: 5, z: -1}
	  dir: {x: 0, y: 0, z: 1}
	  fov: 75

lights:
	- type: POINT
	  pos: {x: 4, y: 15, z: 10}
	  color: 0xF6E392
	  intensity: 1.0

objects:
	- type: SPHERE
	  scale: 2
	  pos: {x: 0, y: 1, z: 10}
	  dir: {x: 0, y: 0, z: 1}
	  material:
		  color: 0x364A90
		  ambient: 0.025
		  diffuse: 0.975
		  specular: 1.0
		  shininess: 256
		  reflect: 0.5
		  refract: 0.1

	- type: PLANE
	  scale: 1
	  pos: {x: 0, y: 0, z: 0}
	  dir: {x: 0, y: 1, z: 0}
	  material:
		  color: 0xDA5930
		  ambient: 0.025
		  diffuse: 0.975
		  specular: 1.0
		  shininess: 256
		  reflect: 0.5
		  refract: 0

...
