---
scene:
	velocity: 8
	recursion_reflect: 1
	recursion_refract: 1
	mouse_sensibility: 0.4
	mouse_interpolation: true
	load_resync: false
	load_percent: false

cameras:
	- camera:
	  pos: {x: 0, y: 1, z: -2}
	  dir: {x: 0, y: 0, z: 0}
	  fov: 100
	  supersampling: 1

	- camera:
	  pos: {x: 0, y: 2, z: 0}
	  dir: {x: 0, y: 0, z: 15}
	  fov: 100
	  supersampling: 1

lights:
	- light:
	  type: POINT
	  pos: {x: 0, y: 5, z: 10}
	  color: 0xF6E392
	  intensity: 1.6
	  attenuation: 0.01
	  shadow: HARD

objects:
	- object:
	  type: SPHERE
	  scale: 2
	  pos: {x: 0, y: 1, z: 5}
	  dir: {x: 0, y: 0, z: 1}
	  material:
		  color: 0x4F4F4F
		  ambient: 0.025
		  diffuse: 0.275
		  specular: 0.7
		  shininess: 1024
		  reflect: 0
		  refract: 1.53
		  transparency: 0.9
		  absorbtion: 0.9

objects:
	- object:
	  type: PLANE
	  scale: 1
	  pos: {x: 0, y: -0.1, z: 0}
	  dir: {x: 0, y: 1, z: 0}
	  material:
		  color: #426CA3
		  ambient: 0.125
		  diffuse: 0.875
		  specular: 0.9
		  shininess: 512
		  reflect: 0
		  refract: 0
		  transparency: 1.0
		  absorbtion: 0.7

	- object:
	  type: CONE
	  scale: 0.5
	  pos: {x: 3, y: 2, z: 6}
	  dir: {x: 0.5, y: 1, z: 0}
	  material:
		  color: 0x93DD4A
		  ambient: 0.125
		  diffuse: 0.775
		  specular: 8.0
		  shininess: 512
		  reflect: 0
		  refract: 0
		  transparency: 0
		  absorbtion: 0.7

	- object:
	  type: CYLINDER
	  scale: 2
	  pos: {x: -4, y: 0, z: 15}
	  dir: {x: -1, y: 1, z: 0}
	  min: -4
	  max: 16
	  material:
		  color: #DF3156
		  ambient: 0.125
		  diffuse: 0.875
		  specular: 2.0
		  shininess: 512
		  reflect: 0
		  refract: 0
		  transparency: 0
		  absorbtion: 0.7
          texture: ../texture/wood1.bmp

...
